package com.force5solutions.care.ldap

enum Permission {

    CAN_ADD_CONTRACTOR_LOCATION('CAN_ADD_CONTRACTOR_LOCATION'),
    CAN_ACCESS_PERSONNEL_MENU('CAN_ACCESS_PERSONNEL_MENU'),
    CAN_ACCESS_REPORTS_MENU('CAN_ACCESS_REPORTS_MENU'),
    CAN_ACCESS_CONTACTS_MENU('CAN_ACCESS_CONTACTS_MENU'),
    CAN_ACCESS_ADMIN_MENU('CAN_ACCESS_ADMIN_MENU'),
    EDIT_RSS_FEEDS('EDIT_RSS_FEEDS'),
    ADD_NEWS_AND_NOTES('ADD_NEWS_AND_NOTES'),

    CREATE_VENDOR('CREATE_VENDOR'),
    READ_VENDOR('READ_VENDOR'),
    UPDATE_VENDOR('UPDATE_VENDOR'),
    DELETE_VENDOR('DELETE_VENDOR'),

    CREATE_CONTRACTOR_SUP('CREATE_CONTRACTOR_SUP'),
    READ_CONTRACTOR_SUP('READ_CONTRACTOR_SUP'),
    UPDATE_CONTRACTOR_SUP('UPDATE_CONTRACTOR_SUP'),
    DELETE_CONTRACTOR_SUP('DELETE_CONTRACTOR_SUP'),

    CREATE_EMPLOYEE_SUP('CREATE_EMPLOYEE_SUP'),
    READ_EMPLOYEE_SUP('READ_EMPLOYEE_SUP'),
    UPDATE_EMPLOYEE_SUP('UPDATE_EMPLOYEE_SUP'),
    DELETE_EMPLOYEE_SUP('DELETE_EMPLOYEE_SUP'),

    CREATE_BUR('CREATE_BUR'),
    READ_BUR('READ_BUR'),
    UPDATE_BUR('UPDATE_BUR'),
    DELETE_BUR('DELETE_BUR'),

    CREATE_BUSINESS_UNIT('CREATE_BUSINESS_UNIT'),
    READ_BUSINESS_UNIT('READ_BUSINESS_UNIT'),
    UPDATE_BUSINESS_UNIT('UPDATE_BUSINESS_UNIT'),
    DELETE_BUSINESS_UNIT('DELETE_BUSINESS_UNIT'),

    CREATE_CONTRACTOR_PROFILE('CREATE_CONTRACTOR_PROFILE'),
    READ_CONTRACTOR_PROFILE('READ_CONTRACTOR_PROFILE'),
    UPDATE_CONTRACTOR_PROFILE('UPDATE_CONTRACTOR_PROFILE'),
    DELETE_CONTRACTOR_PROFILE('DELETE_CONTRACTOR_PROFILE'),

    CREATE_CONTRACTOR_ACCESS('CREATE_CONTRACTOR_ACCESS'),
    READ_CONTRACTOR_ACCESS('READ_CONTRACTOR_ACCESS'),
    UPDATE_CONTRACTOR_ACCESS('UPDATE_CONTRACTOR_ACCESS'),
    DELETE_CONTRACTOR_ACCESS('DELETE_CONTRACTOR_ACCESS'),

    CREATE_CONTRACTOR_CERTIFICATION('CREATE_CONTRACTOR_CERTIFICATION'),
    READ_CONTRACTOR_CERTIFICATION('READ_CONTRACTOR_CERTIFICATION'),
    UPDATE_CONTRACTOR_CERTIFICATION('UPDATE_CONTRACTOR_CERTIFICATION'),
    DELETE_CONTRACTOR_CERTIFICATION('DELETE_CONTRACTOR_CERTIFICATION'),
    RENEW_CONTRACTOR_CERTIFICATION('RENEW_CONTRACTOR_CERTIFICATION'),

    CREATE_EMPLOYEE_PROFILE('CREATE_EMPLOYEE_PROFILE'),
    READ_EMPLOYEE_PROFILE('READ_EMPLOYEE_PROFILE'),
    UPDATE_EMPLOYEE_PROFILE('UPDATE_EMPLOYEE_PROFILE'),
    DELETE_EMPLOYEE_PROFILE('DELETE_EMPLOYEE_PROFILE'),

    CREATE_EMPLOYEE_ACCESS('CREATE_EMPLOYEE_ACCESS'),
    READ_EMPLOYEE_ACCESS('READ_EMPLOYEE_ACCESS'),
    UPDATE_EMPLOYEE_ACCESS('UPDATE_EMPLOYEE_ACCESS'),
    DELETE_EMPLOYEE_ACCESS('DELETE_EMPLOYEE_ACCESS'),

    CREATE_EMPLOYEE_CERTIFICATION('CREATE_EMPLOYEE_CERTIFICATION'),
    READ_EMPLOYEE_CERTIFICATION('READ_EMPLOYEE_CERTIFICATION'),
    UPDATE_EMPLOYEE_CERTIFICATION('UPDATE_EMPLOYEE_CERTIFICATION'),
    DELETE_EMPLOYEE_CERTIFICATION('DELETE_EMPLOYEE_CERTIFICATION'),
    RENEW_EMPLOYEE_CERTIFICATION('RENEW_EMPLOYEE_CERTIFICATION'),

    CREATE_COURSE('CREATE_COURSE'),
    READ_COURSE('READ_COURSE'),
    UPDATE_COURSE('UPDATE_COURSE'),
    DELETE_COURSE('DELETE_COURSE'),

    CREATE_CERTIFICATION('CREATE_CERTIFICATION'),
    READ_CERTIFICATION('READ_CERTIFICATION'),
    UPDATE_CERTIFICATION('UPDATE_CERTIFICATION'),
    DELETE_CERTIFICATION('DELETE_CERTIFICATION'),

    CREATE_COMPANY_NODE('CREATE_COMPANY_NODE'),
    CREATE_LOCATION('CREATE_LOCATION'),
    READ_LOCATION('READ_LOCATION'),
    UPDATE_LOCATION('UPDATE_LOCATION'),
    DELETE_LOCATION('DELETE_LOCATION'),

    CREATE_MESSAGE_TEMPLATE('CREATE_MESSAGE_TEMPLATE'),
    READ_MESSAGE_TEMPLATE('READ_MESSAGE_TEMPLATE'),
    UPDATE_MESSAGE_TEMPLATE('UPDATE_MESSAGE_TEMPLATE'),
    DELETE_MESSAGE_TEMPLATE('DELETE_MESSAGE_TEMPLATE'),

    CREATE_ALERT('CREATE_ALERT'),
    READ_ALERT('READ_ALERT'),
    UPDATE_ALERT('UPDATE_ALERT'),
    DELETE_ALERT('DELETE_ALERT'),

    REQUEST_CONTRACTOR_ACCESS('REQUEST_CONTRACTOR_ACCESS'),
    REQUEST_CONTRACTOR_REVOKE('REQUEST_CONTRACTOR_REVOKE'),
    REQUEST_CONTRACTOR_TERMINATE('REQUEST_CONTRACTOR_TERMINATE'),

    REQUEST_EMPLOYEE_ACCESS('REQUEST_EMPLOYEE_ACCESS'),
    REQUEST_EMPLOYEE_REVOKE('REQUEST_EMPLOYEE_REVOKE'),
    REQUEST_EMPLOYEE_TERMINATE('REQUEST_EMPLOYEE_TERMINATE'),

    CREATE_ENTITLEMENT_ROLE('CREATE_ENTITLEMENT_ROLE'),
    READ_ENTITLEMENT_ROLE('READ_ENTITLEMENT_ROLE'),
    UPDATE_ENTITLEMENT_ROLE('UPDATE_ENTITLEMENT_ROLE'),
    DELETE_ENTITLEMENT_ROLE('DELETE_ENTITLEMENT_ROLE'),

    CREATE_ENTITLEMENT_POLICY('CREATE_ENTITLEMENT_POLICY'),
    READ_ENTITLEMENT_POLICY('READ_ENTITLEMENT_POLICY'),
    UPDATE_ENTITLEMENT_POLICY('UPDATE_ENTITLEMENT_POLICY'),
    DELETE_ENTITLEMENT_POLICY('DELETE_ENTITLEMENT_POLICY'),

    READ_MANAGE_WORKFLOW('READ_MANAGE_WORKFLOW'),

    CREATE_ENTITLEMENT('CREATE_ENTITLEMENT'),
    READ_ENTITLEMENT('READ_ENTITLEMENT'),
    UPDATE_ENTITLEMENT('UPDATE_ENTITLEMENT'),
    DELETE_ENTITLEMENT('DELETE_ENTITLEMENT'),

    CREATE_ORIGIN('CREATE_ORIGIN'),
    READ_ORIGIN('READ_ORIGIN'),
    UPDATE_ORIGIN('UPDATE_ORIGIN'),
    DELETE_ORIGIN('DELETE_ORIGIN'),

    CREATE_ROLE_OWNER('CREATE_ROLE_OWNER'),
    READ_ROLE_OWNER('READ_ROLE_OWNER'),
    UPDATE_ROLE_OWNER('UPDATE_ROLE_OWNER'),
    DELETE_ROLE_OWNER('DELETE_ROLE_OWNER'),

    CREATE_PROVISIONER('CREATE_PROVISIONER'),
    READ_PROVISIONER('READ_PROVISIONER'),
    UPDATE_PROVISIONER('UPDATE_PROVISIONER'),
    DELETE_PROVISIONER('DELETE_PROVISIONER'),

    CREATE_DEPROVISIONER('CREATE_DEPROVISIONER'),
    READ_DEPROVISIONER('READ_DEPROVISIONER'),
    UPDATE_DEPROVISIONER('UPDATE_DEPROVISIONER'),
    DELETE_DEPROVISIONER('DELETE_DEPROVISIONER'),

    CREATE_GATEKEEPER('CREATE_GATEKEEPER'),
    READ_GATEKEEPER('READ_GATEKEEPER'),
    UPDATE_GATEKEEPER('UPDATE_GATEKEEPER'),
    DELETE_GATEKEEPER('DELETE_GATEKEEPER'),

    CREATE_SECURITY_ROLE('CREATE_SECURITY_ROLE'),
    READ_SECURITY_ROLE('READ_SECURITY_ROLE'),
    UPDATE_SECURITY_ROLE('UPDATE_SECURITY_ROLE'),
    DELETE_SECURITY_ROLE('DELETE_SECURITY_ROLE'),

    CAN_ACCESS_ENTITLEMENT_ROLE_MENU('CAN_ACCESS_ENTITLEMENT_ROLE_MENU'),
    CAN_ACCESS_ENTITLEMENT_MENU('CAN_ACCESS_ENTITLEMENT_MENU'),

    DASHBOARD_WITH_LINKS('DASHBOARD_WITH_LINKS')

    private final String name

    Permission(String name) {
        this.name = name
    }

    public String toString() {
        return name
    }

}
